"""Adapter protocols — structural contracts for STT, TTS, and Agent backends."""

from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Protocol, runtime_checkable


@runtime_checkable
class STTPort(Protocol):
    """Contract for speech-to-text adapters."""

    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def start_utterance(self) -> None: ...
    async def stream(self, audio_chunk: bytes) -> None: ...
    async def finish_utterance(self) -> str: ...


@runtime_checkable
class TTSPort(Protocol):
    """Contract for text-to-speech adapters."""

    async def synthesize(self, text: str) -> AsyncIterator[bytes]: ...
    async def stop(self) -> None: ...


@runtime_checkable
class AgentPort(Protocol):
    """Contract for agent/LLM adapters."""

    @property
    def agent_id(self) -> str: ...
    async def connect(self, agent_id: str) -> None: ...
    async def disconnect(self) -> None: ...
    async def is_connected(self) -> bool: ...
    async def send(self, text: str) -> AsyncIterator[str]: ...
    async def resolve_agent_id(self, agent_name: str) -> str: ...
